import type { Service, Booking, DashboardStats } from '../types';

/* ─── MOCK SERVICES ─────────────────────────────────────────────────── */
export const MOCK_SERVICES: Service[] = [
  {
    id: '1',
    title: 'Dental Consultation',
    description: 'Complete dental examination and consultation with our expert dentists.',
    duration: '45 minutes',
    price: 50,
    status: 'active',
    createdAt: '2024-01-10T09:00:00Z',
  },
  {
    id: '2',
    title: 'General Medical Consultation',
    description: 'Comprehensive general health check-up and medical consultation.',
    duration: '45 minutes',
    price: 70,
    status: 'active',
    createdAt: '2024-01-10T09:00:00Z',
  },
  {
    id: '3',
    title: 'Eye Examination',
    description: 'Thorough eye examination including vision testing and eye health assessment.',
    duration: '60 minutes',
    price: 80,
    status: 'active',
    createdAt: '2024-01-10T09:00:00Z',
  },
  {
    id: '4',
    title: 'Physiotherapy Session',
    description: 'Professional physiotherapy for musculoskeletal pain and rehabilitation.',
    duration: '60 minutes',
    price: 90,
    status: 'active',
    createdAt: '2024-01-11T09:00:00Z',
  },
  {
    id: '5',
    title: 'Cardiology Consultation',
    description: 'Heart health screening and cardiology specialist consultation.',
    duration: '60 minutes',
    price: 120,
    status: 'active',
    createdAt: '2024-01-12T09:00:00Z',
  },
  {
    id: '6',
    title: 'Dermatology Consultation',
    description: 'Skin condition assessment and dermatology consultation.',
    duration: '30 minutes',
    price: 60,
    status: 'inactive',
    createdAt: '2024-01-13T09:00:00Z',
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: '1',
    customerName: 'James Wilson',
    customerEmail: 'james.wilson@email.com',
    customerPhone: '+1 555-0101',
    serviceId: '1',
    service: MOCK_SERVICES[0],
    bookingDate: '2024-07-15',
    bookingTime: '09:00',
    notes: 'First time patient, has dental anxiety.',
    status: 'confirmed',
    createdAt: '2024-07-10T09:00:00Z',
  },
  {
    id: '2',
    customerName: 'Sarah Johnson',
    customerEmail: 'sarah.j@email.com',
    customerPhone: '+1 555-0102',
    serviceId: '2',
    service: MOCK_SERVICES[1],
    bookingDate: '2024-07-16',
    bookingTime: '10:30',
    notes: '',
    status: 'pending',
    createdAt: '2024-07-11T10:00:00Z',
  },
  {
    id: '3',
    customerName: 'Michael Chen',
    customerEmail: 'michael.c@email.com',
    customerPhone: '+1 555-0103',
    serviceId: '3',
    service: MOCK_SERVICES[2],
    bookingDate: '2024-07-14',
    bookingTime: '14:00',
    notes: 'Regular eye checkup.',
    status: 'completed',
    createdAt: '2024-07-09T08:00:00Z',
  },
  {
    id: '4',
    customerName: 'Emily Davis',
    customerEmail: 'emily.d@email.com',
    customerPhone: '+1 555-0104',
    serviceId: '4',
    service: MOCK_SERVICES[3],
    bookingDate: '2024-07-17',
    bookingTime: '11:00',
    notes: 'Lower back pain treatment.',
    status: 'pending',
    createdAt: '2024-07-12T11:00:00Z',
  },
  {
    id: '5',
    customerName: 'Robert Martinez',
    customerEmail: 'robert.m@email.com',
    customerPhone: '+1 555-0105',
    serviceId: '5',
    service: MOCK_SERVICES[4],
    bookingDate: '2024-07-13',
    bookingTime: '15:30',
    notes: 'Follow-up after medication.',
    status: 'cancelled',
    createdAt: '2024-07-08T14:00:00Z',
  },
  {
    id: '6',
    customerName: 'Linda Thompson',
    customerEmail: 'linda.t@email.com',
    customerPhone: '+1 555-0106',
    serviceId: '1',
    service: MOCK_SERVICES[0],
    bookingDate: '2024-07-18',
    bookingTime: '09:30',
    notes: '',
    status: 'pending',
    createdAt: '2024-07-13T09:30:00Z',
  },
];

export const MOCK_STATS: DashboardStats = {
  totalServices: 12,
  totalBookings: 150,
  pendingAppointments: 20,
  completedAppointments: 100,
};
